# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'ICSGameLauncher.slnx'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '10.x'
      includePreviewVersions: true

  - task: CmdLine@2
    displayName: 'Install Make'
    inputs:
      script: 'choco install make --yes'

  - task: Cache@2
    displayName: 'Cache NuGet packages'
    inputs:
      key: 'nuget | "$(Agent.OS)" | **/*.csproj'
      restoreKeys: |
        nuget | "$(Agent.OS)"
      path: '$(USERPROFILE)/.nuget/packages'

  - task: CmdLine@2
    displayName: 'Install MAUI workload'
    inputs:
      script: 'dotnet workload restore $(solution)'

  - task: CmdLine@2
    displayName: 'Build and Test via Makefile'
    inputs:
      script: 'make test CONFIGURATION=Release'

  - task: PublishTestResults@2
    displayName: 'Publish test results'
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/*.trx'
    condition: succeededOrFailed()