# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'ICSGameLauncher.slnx'
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '10.x'
      includePreviewVersions: true

  - task: CmdLine@2
    displayName: 'Install MAUI workload'
    inputs:
      script: 'dotnet workload install maui'

  - task: CmdLine@2
    displayName: 'Restore'
    inputs:
      script: 'dotnet restore $(solution)'

  - task: CmdLine@2
    displayName: 'Build'
    inputs:
      script: 'dotnet build $(solution) --configuration $(buildConfiguration) --no-restore /p:Platform="Any CPU" /p:SelfContained=false /m:1'

  - task: CmdLine@2
    displayName: 'Test'
    inputs:
      script: 'dotnet test $(solution) --configuration $(buildConfiguration) --no-build --verbosity normal'
